#!/bin/bash

echo "Creating a new 1Password login for Andrew..."
read -p 'Username: ' uservar
read -p 'Title: ' title

read -p 'Do you want me to generate a secure password automatically? ' autopass

if [[ $autopass == "Y" || $autopass == "y" ]]; then
    passvar=`date +%s | sha256sum | base64 | head -c 24`
else
    read -sp 'Password: ' passvar
fi

#op create item Login $payload --title=$title

payload=`op get template Login | jq --arg u "$uservar" '.fields[0].value=$u' | jq --arg p "$passvar" '.fields[1].value=$p' | op encode`

op create item Login $payload --title=$title

